# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Mon Apr 27 13:47:07 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 751, 541))
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.welcome_pic = QtWidgets.QLabel(self.welcome)
        self.welcome_pic.setGeometry(QtCore.QRect(50, 90, 651, 421))
        self.welcome_pic.setText("")
        self.welcome_pic.setPixmap(QtGui.QPixmap("pics/pic1.jpg"))
        self.welcome_pic.setObjectName("welcome_pic")
        self.label_2 = QtWidgets.QLabel(self.welcome)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 691, 471))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pfa/pics/pic1.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.welcome)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 71, 17))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.welcome)
        self.liste_emp = QtWidgets.QWidget()
        self.liste_emp.setObjectName("liste_emp")
        self.labelrecherche_3 = QtWidgets.QLabel(self.liste_emp)
        self.labelrecherche_3.setGeometry(QtCore.QRect(60, 50, 111, 17))
        self.labelrecherche_3.setObjectName("labelrecherche_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.liste_emp)
        self.tableWidget_3.setGeometry(QtCore.QRect(60, 210, 641, 192))
        self.tableWidget_3.setMaximumSize(QtCore.QSize(681, 192))
        self.tableWidget_3.setAlternatingRowColors(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(70)
        self.gridLayoutWidget = QtWidgets.QWidget(self.liste_emp)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 80, 621, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.naissance_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.naissance_5.setObjectName("naissance_5")
        self.gridLayout.addWidget(self.naissance_5, 0, 5, 1, 1)
        self.cin_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cin_5.setObjectName("cin_5")
        self.gridLayout.addWidget(self.cin_5, 0, 3, 1, 1)
        self.prenom_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.prenom_5.setObjectName("prenom_5")
        self.gridLayout.addWidget(self.prenom_5, 1, 3, 1, 1)
        self.embauche_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.embauche_5.setObjectName("embauche_5")
        self.gridLayout.addWidget(self.embauche_5, 1, 1, 1, 1)
        self.matricule_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.matricule_5.setObjectName("matricule_5")
        self.gridLayout.addWidget(self.matricule_5, 0, 1, 1, 1)
        self.labelmatricule_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelmatricule_5.setObjectName("labelmatricule_5")
        self.gridLayout.addWidget(self.labelmatricule_5, 0, 2, 1, 1)
        self.labelcin_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelcin_5.setObjectName("labelcin_5")
        self.gridLayout.addWidget(self.labelcin_5, 0, 0, 1, 1)
        self.labelprenom_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelprenom_5.setObjectName("labelprenom_5")
        self.gridLayout.addWidget(self.labelprenom_5, 1, 2, 1, 1)
        self.labelnom_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelnom_5.setObjectName("labelnom_5")
        self.gridLayout.addWidget(self.labelnom_5, 1, 0, 1, 1)
        self.labelnaissance_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelnaissance_5.setObjectName("labelnaissance_5")
        self.gridLayout.addWidget(self.labelnaissance_5, 0, 4, 1, 1)
        self.nom_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nom_5.setObjectName("nom_5")
        self.gridLayout.addWidget(self.nom_5, 1, 5, 1, 1)
        self.labelembauche_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelembauche_5.setObjectName("labelembauche_5")
        self.gridLayout.addWidget(self.labelembauche_5, 1, 4, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.liste_emp)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 440, 611, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ajouter_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ajouter_3.setObjectName("ajouter_3")
        self.horizontalLayout.addWidget(self.ajouter_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.importer_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.importer_3.setObjectName("importer_3")
        self.horizontalLayout.addWidget(self.importer_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.supprimer_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.supprimer_3.setObjectName("supprimer_3")
        self.horizontalLayout.addWidget(self.supprimer_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.Modifier_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Modifier_3.setObjectName("Modifier_3")
        self.horizontalLayout.addWidget(self.Modifier_3)
        self.stackedWidget.addWidget(self.liste_emp)
        self.ajouter_emp = QtWidgets.QWidget()
        self.ajouter_emp.setObjectName("ajouter_emp")
        self.formLayoutWidget = QtWidgets.QWidget(self.ajouter_emp)
        self.formLayoutWidget.setGeometry(QtCore.QRect(170, 70, 401, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.matricule = QtWidgets.QLabel(self.formLayoutWidget)
        self.matricule.setObjectName("matricule")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.matricule)
        self.line_mat = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_mat.setObjectName("line_mat")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_mat)
        self.cin = QtWidgets.QLabel(self.formLayoutWidget)
        self.cin.setObjectName("cin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cin)
        self.line_cin = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_cin.setObjectName("line_cin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_cin)
        self.nom = QtWidgets.QLabel(self.formLayoutWidget)
        self.nom.setObjectName("nom")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nom)
        self.line_nom = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_nom.setObjectName("line_nom")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_nom)
        self.prenom = QtWidgets.QLabel(self.formLayoutWidget)
        self.prenom.setObjectName("prenom")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.prenom)
        self.line_prenom = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_prenom.setObjectName("line_prenom")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_prenom)
        self.naiss = QtWidgets.QLabel(self.formLayoutWidget)
        self.naiss.setObjectName("naiss")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.naiss)
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.date_emb = QtWidgets.QLabel(self.formLayoutWidget)
        self.date_emb.setObjectName("date_emb")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.date_emb)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.parcourir = QtWidgets.QToolButton(self.formLayoutWidget)
        self.parcourir.setObjectName("parcourir")
        self.horizontalLayout_2.addWidget(self.parcourir)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.ajouter_emp)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(220, 360, 301, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.annuler = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.annuler.setObjectName("annuler")
        self.horizontalLayout_6.addWidget(self.annuler)
        self.stackedWidget.addWidget(self.ajouter_emp)
        self.details_gamme = QtWidgets.QWidget()
        self.details_gamme.setObjectName("details_gamme")
        self.recherche = QtWidgets.QLabel(self.details_gamme)
        self.recherche.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.recherche.setObjectName("recherche")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.details_gamme)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(50, 90, 661, 80))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.nom_modele = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.nom_modele.setObjectName("nom_modele")
        self.horizontalLayout_15.addWidget(self.nom_modele)
        self.nom_mod = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.nom_mod.setObjectName("nom_mod")
        self.horizontalLayout_15.addWidget(self.nom_mod)
        self.code_modele = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.code_modele.setObjectName("code_modele")
        self.horizontalLayout_15.addWidget(self.code_modele)
        self.code_mod = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.code_mod.setObjectName("code_mod")
        self.horizontalLayout_15.addWidget(self.code_mod)
        self.marque = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.marque.setObjectName("marque")
        self.horizontalLayout_15.addWidget(self.marque)
        self.marque_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.marque_2.setObjectName("marque_2")
        self.horizontalLayout_15.addWidget(self.marque_2)
        self.gamme = QtWidgets.QTableWidget(self.details_gamme)
        self.gamme.setGeometry(QtCore.QRect(210, 220, 311, 211))
        self.gamme.setObjectName("gamme")
        self.gamme.setColumnCount(3)
        self.gamme.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setHorizontalHeaderItem(2, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.details_gamme)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 440, 491, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ajouter = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ajouter.setObjectName("ajouter")
        self.horizontalLayout_3.addWidget(self.ajouter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.importer = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.importer.setObjectName("importer")
        self.horizontalLayout_3.addWidget(self.importer)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.supprimer = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.supprimer.setObjectName("supprimer")
        self.horizontalLayout_3.addWidget(self.supprimer)
        self.stackedWidget.addWidget(self.details_gamme)
        self.operation = QtWidgets.QWidget()
        self.operation.setObjectName("operation")
        self.recherche_2 = QtWidgets.QLabel(self.operation)
        self.recherche_2.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.recherche_2.setObjectName("recherche_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.operation)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 90, 691, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.code_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.code_op.setObjectName("code_op")
        self.horizontalLayout_4.addWidget(self.code_op)
        self.code_oper = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.code_oper.setObjectName("code_oper")
        self.horizontalLayout_4.addWidget(self.code_oper)
        self.nom_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.nom_op.setObjectName("nom_op")
        self.horizontalLayout_4.addWidget(self.nom_op)
        self.nom_oper = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.nom_oper.setObjectName("nom_oper")
        self.horizontalLayout_4.addWidget(self.nom_oper)
        self.machine = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.machine.setObjectName("machine")
        self.horizontalLayout_4.addWidget(self.machine)
        self.machin = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.machin.setObjectName("machin")
        self.horizontalLayout_4.addWidget(self.machin)
        self.tableWidget = QtWidgets.QTableWidget(self.operation)
        self.tableWidget.setGeometry(QtCore.QRect(120, 200, 511, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.operation)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 410, 621, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.importer_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.importer_2.setObjectName("importer_2")
        self.horizontalLayout_5.addWidget(self.importer_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.ajouter_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ajouter_2.setObjectName("ajouter_2")
        self.horizontalLayout_5.addWidget(self.ajouter_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.modifier = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.modifier.setObjectName("modifier")
        self.horizontalLayout_5.addWidget(self.modifier)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.supprimer_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.supprimer_2.setObjectName("supprimer_2")
        self.horizontalLayout_5.addWidget(self.supprimer_2)
        self.stackedWidget.addWidget(self.operation)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 25))
        self.menubar.setObjectName("menubar")
        self.menuGestion_Employes = QtWidgets.QMenu(self.menubar)
        self.menuGestion_Employes.setObjectName("menuGestion_Employes")
        self.menuGestion_Operations = QtWidgets.QMenu(self.menubar)
        self.menuGestion_Operations.setObjectName("menuGestion_Operations")
        self.menu_quilibrage = QtWidgets.QMenu(self.menubar)
        self.menu_quilibrage.setObjectName("menu_quilibrage")
        self.menuStatistiqus = QtWidgets.QMenu(self.menubar)
        self.menuStatistiqus.setObjectName("menuStatistiqus")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Liste_Employes = QtWidgets.QAction(MainWindow)
        self.Liste_Employes.setIconVisibleInMenu(False)
        self.Liste_Employes.setObjectName("Liste_Employes")
        self.Competences = QtWidgets.QAction(MainWindow)
        self.Competences.setObjectName("Competences")
        self.actionDetails_Gamme = QtWidgets.QAction(MainWindow)
        self.actionDetails_Gamme.setObjectName("actionDetails_Gamme")
        self.actionDetails_Operation = QtWidgets.QAction(MainWindow)
        self.actionDetails_Operation.setObjectName("actionDetails_Operation")
        self.actionDetail_equilibrage = QtWidgets.QAction(MainWindow)
        self.actionDetail_equilibrage.setObjectName("actionDetail_equilibrage")
        self.actionListe_equilibrage = QtWidgets.QAction(MainWindow)
        self.actionListe_equilibrage.setObjectName("actionListe_equilibrage")
        self.menuGestion_Employes.addAction(self.Liste_Employes)
        self.menuGestion_Employes.addAction(self.Competences)
        self.menuGestion_Operations.addAction(self.actionDetails_Gamme)
        self.menuGestion_Operations.addAction(self.actionDetails_Operation)
        self.menu_quilibrage.addAction(self.actionDetail_equilibrage)
        self.menu_quilibrage.addAction(self.actionListe_equilibrage)
        self.menubar.addAction(self.menuGestion_Employes.menuAction())
        self.menubar.addAction(self.menuGestion_Operations.menuAction())
        self.menubar.addAction(self.menu_quilibrage.menuAction())
        self.menubar.addAction(self.menuStatistiqus.menuAction())
	
       	self.retranslateUi(MainWindow)
        self.Liste_Employes.triggered.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_emp))
        self.ajouter_3.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.ajouter_emp))
        self.annuler.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_emp))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow): 
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Welcome"))
        self.labelrecherche_3.setText(_translate("MainWindow", "Rechercher par:"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Matricule"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CIN"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nom"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Prénom"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Naissance"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date d\'Embauche"))
        self.labelmatricule_5.setText(_translate("MainWindow", "Matricule:"))
        self.labelcin_5.setText(_translate("MainWindow", "CIN :"))
        self.labelprenom_5.setText(_translate("MainWindow", "Prénom :"))
        self.labelnom_5.setText(_translate("MainWindow", "Nom :"))
        self.labelnaissance_5.setText(_translate("MainWindow", "Date Naissance:"))
        self.labelembauche_5.setText(_translate("MainWindow", "Date Embauche:"))
        self.ajouter_3.setText(_translate("MainWindow", "Ajouter"))
        self.importer_3.setText(_translate("MainWindow", "Importer"))
        self.supprimer_3.setText(_translate("MainWindow", "Supprimer"))
        self.Modifier_3.setText(_translate("MainWindow", "Modifier"))
        self.matricule.setText(_translate("MainWindow", "Matricule"))
        self.cin.setText(_translate("MainWindow", "CIN"))
        self.nom.setText(_translate("MainWindow", "Nom"))
        self.prenom.setText(_translate("MainWindow", "Prénom"))
        self.naiss.setText(_translate("MainWindow", "Date Naissance"))
        self.date_emb.setText(_translate("MainWindow", "Date Embauche"))
        self.label.setText(_translate("MainWindow", "Photo"))
        self.parcourir.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "Ajouter"))
        self.annuler.setText(_translate("MainWindow", "Annuler"))
        self.recherche.setText(_translate("MainWindow", "Rechercher par:"))
        self.nom_modele.setText(_translate("MainWindow", "Nom Modèle:"))
        self.code_modele.setText(_translate("MainWindow", "Code Modèle:"))
        self.marque.setText(_translate("MainWindow", "Marque:"))
        item = self.gamme.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom Modèle"))
        item = self.gamme.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code modèle"))
        item = self.gamme.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Marque"))
        self.ajouter.setText(_translate("MainWindow", "Ajouter"))
        self.importer.setText(_translate("MainWindow", "Importer"))
        self.supprimer.setText(_translate("MainWindow", "Supprimer"))
        self.recherche_2.setText(_translate("MainWindow", "Rechercher par: "))
        self.code_op.setText(_translate("MainWindow", "Code Opération:"))
        self.nom_op.setText(_translate("MainWindow", "Nom Opération:"))
        self.machine.setText(_translate("MainWindow", "Machine: "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code Opération"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom Opération"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Minutage"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Machine"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Critère de Qualité"))
        self.importer_2.setText(_translate("MainWindow", "Importer"))
        self.ajouter_2.setText(_translate("MainWindow", "Ajouter"))
        self.modifier.setText(_translate("MainWindow", "Modifier"))
        self.supprimer_2.setText(_translate("MainWindow", "Supprimer"))
        self.menuGestion_Employes.setTitle(_translate("MainWindow", "Gestion Employés"))
        self.menuGestion_Operations.setTitle(_translate("MainWindow", "Gestion Opérations"))
        self.menu_quilibrage.setTitle(_translate("MainWindow", "Équilibrage"))
        self.menuStatistiqus.setTitle(_translate("MainWindow", "Consulter Statistiques"))
        self.Liste_Employes.setText(_translate("MainWindow", "Liste Employés"))
        self.Competences.setText(_translate("MainWindow", "Compétences"))
        self.actionDetails_Gamme.setText(_translate("MainWindow", "Détails Gamme"))
        self.actionDetails_Operation.setText(_translate("MainWindow", "Détails Opération"))
        self.actionDetail_equilibrage.setText(_translate("MainWindow", "Créer Équilibrage"))
        self.actionListe_equilibrage.setText(_translate("MainWindow", "Liste Équilibrage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

