# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Mon May 11 01:34:34 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 831, 541))
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.page_name_welcome = QtWidgets.QLabel(self.welcome)
        self.page_name_welcome.setGeometry(QtCore.QRect(270, 120, 111, 61))
        self.page_name_welcome.setObjectName("page_name_welcome")
        self.stackedWidget.addWidget(self.welcome)
        self.liste_emp = QtWidgets.QWidget()
        self.liste_emp.setObjectName("liste_emp")
        self.labelrecherche_emp = QtWidgets.QLabel(self.liste_emp)
        self.labelrecherche_emp.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.labelrecherche_emp.setObjectName("labelrecherche_emp")
        self.table_emp = QtWidgets.QTableWidget(self.liste_emp)
        self.table_emp.setGeometry(QtCore.QRect(100, 270, 611, 151))
        self.table_emp.setMaximumSize(QtCore.QSize(681, 192))
        self.table_emp.setAlternatingRowColors(True)
        self.table_emp.setObjectName("table_emp")
        self.table_emp.setColumnCount(6)
        self.table_emp.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_emp.setHorizontalHeaderItem(5, item)
        self.table_emp.horizontalHeader().setMinimumSectionSize(70)
        self.namepage_emp = QtWidgets.QLabel(self.liste_emp)
        self.namepage_emp.setGeometry(QtCore.QRect(40, 10, 131, 17))
        self.namepage_emp.setObjectName("namepage_emp")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.liste_emp)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(90, 80, 621, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelnaissance_emp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelnaissance_emp.setObjectName("labelnaissance_emp")
        self.gridLayout_2.addWidget(self.labelnaissance_emp, 0, 4, 1, 1)
        self.labelmatricul_emp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelmatricul_emp.setObjectName("labelmatricul_emp")
        self.gridLayout_2.addWidget(self.labelmatricul_emp, 0, 2, 1, 1)
        self.labelprenom_emp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelprenom_emp.setObjectName("labelprenom_emp")
        self.gridLayout_2.addWidget(self.labelprenom_emp, 1, 2, 1, 1)
        self.mat_emp = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.mat_emp.setObjectName("mat_emp")
        self.gridLayout_2.addWidget(self.mat_emp, 0, 3, 1, 1)
        self.labelcin_emp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelcin_emp.setObjectName("labelcin_emp")
        self.gridLayout_2.addWidget(self.labelcin_emp, 0, 0, 1, 1)
        self.labelembauche_emp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelembauche_emp.setObjectName("labelembauche_emp")
        self.gridLayout_2.addWidget(self.labelembauche_emp, 1, 4, 1, 1)
        self.cin_emp = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.cin_emp.setObjectName("cin_emp")
        self.gridLayout_2.addWidget(self.cin_emp, 0, 1, 1, 1)
        self.prenom_emp = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.prenom_emp.setObjectName("prenom_emp")
        self.gridLayout_2.addWidget(self.prenom_emp, 1, 3, 1, 1)
        self.labelnom_emp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelnom_emp.setObjectName("labelnom_emp")
        self.gridLayout_2.addWidget(self.labelnom_emp, 1, 0, 1, 1)
        self.nom_emp = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.nom_emp.setObjectName("nom_emp")
        self.gridLayout_2.addWidget(self.nom_emp, 1, 1, 1, 1)
        self.date_nass_emp = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.date_nass_emp.setObjectName("date_nass_emp")
        self.gridLayout_2.addWidget(self.date_nass_emp, 0, 5, 1, 1)
        self.date_emb_emp = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.date_emb_emp.setObjectName("date_emb_emp")
        self.gridLayout_2.addWidget(self.date_emb_emp, 1, 5, 1, 1)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.liste_emp)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(130, 450, 541, 31))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ajouter_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.ajouter_emp.setObjectName("ajouter_emp")
        self.horizontalLayout_10.addWidget(self.ajouter_emp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.importer_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.importer_emp.setObjectName("importer_emp")
        self.horizontalLayout_10.addWidget(self.importer_emp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.Modifier_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.Modifier_emp.setObjectName("Modifier_emp")
        self.horizontalLayout_10.addWidget(self.Modifier_emp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.supprimer_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.supprimer_emp.setObjectName("supprimer_emp")
        self.horizontalLayout_10.addWidget(self.supprimer_emp)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.liste_emp)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(510, 180, 201, 31))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rechercher_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_17)
        self.rechercher_emp.setObjectName("rechercher_emp")
        self.horizontalLayout_14.addWidget(self.rechercher_emp)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.initialiser_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_17)
        self.initialiser_emp.setObjectName("initialiser_emp")
        self.horizontalLayout_14.addWidget(self.initialiser_emp)
        self.stackedWidget.addWidget(self.liste_emp)
        self.ajouter_employe = QtWidgets.QWidget()
        self.ajouter_employe.setObjectName("ajouter_employe")
        self.formLayoutWidget = QtWidgets.QWidget(self.ajouter_employe)
        self.formLayoutWidget.setGeometry(QtCore.QRect(170, 70, 401, 252))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_mat_aj_emp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_mat_aj_emp.setObjectName("label_mat_aj_emp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_mat_aj_emp)
        self.mat_aj_emp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mat_aj_emp.setObjectName("mat_aj_emp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mat_aj_emp)
        self.label_cin_aj_emp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_cin_aj_emp.setObjectName("label_cin_aj_emp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_cin_aj_emp)
        self.cin_aj_emp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cin_aj_emp.setObjectName("cin_aj_emp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cin_aj_emp)
        self.label_nom_aj_emp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_nom_aj_emp.setObjectName("label_nom_aj_emp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_nom_aj_emp)
        self.nom_aj_emp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nom_aj_emp.setObjectName("nom_aj_emp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nom_aj_emp)
        self.label_prenom_aj_emp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_prenom_aj_emp.setObjectName("label_prenom_aj_emp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_prenom_aj_emp)
        self.prenom_aj_emp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.prenom_aj_emp.setObjectName("prenom_aj_emp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.prenom_aj_emp)
        self.naiss_aj_emp = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.naiss_aj_emp.setObjectName("naiss_aj_emp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.naiss_aj_emp)
        self.label_emb_aj_emp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_emb_aj_emp.setObjectName("label_emb_aj_emp")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_emb_aj_emp)
        self.emb_aj_emp = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.emb_aj_emp.setObjectName("emb_aj_emp")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.emb_aj_emp)
        self.label_photo_aj_emp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_photo_aj_emp.setObjectName("label_photo_aj_emp")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_photo_aj_emp)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.photo_aj_emp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.photo_aj_emp.setObjectName("photo_aj_emp")
        self.horizontalLayout_2.addWidget(self.photo_aj_emp)
        self.parcourir = QtWidgets.QToolButton(self.formLayoutWidget)
        self.parcourir.setObjectName("parcourir")
        self.horizontalLayout_2.addWidget(self.parcourir)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_naiss_aj_emp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_naiss_aj_emp.setObjectName("label_naiss_aj_emp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_naiss_aj_emp)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.ajouter_employe)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(170, 410, 401, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.enregistrer_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.enregistrer_emp.setObjectName("enregistrer_emp")
        self.horizontalLayout_6.addWidget(self.enregistrer_emp)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.annuler_emp = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.annuler_emp.setObjectName("annuler_emp")
        self.horizontalLayout_6.addWidget(self.annuler_emp)
        self.namepage_aj_emp = QtWidgets.QLabel(self.ajouter_employe)
        self.namepage_aj_emp.setGeometry(QtCore.QRect(160, 20, 131, 17))
        self.namepage_aj_emp.setObjectName("namepage_aj_emp")
        self.stackedWidget.addWidget(self.ajouter_employe)
        self.details_gamme = QtWidgets.QWidget()
        self.details_gamme.setObjectName("details_gamme")
        self.labelrecherche_gamme = QtWidgets.QLabel(self.details_gamme)
        self.labelrecherche_gamme.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.labelrecherche_gamme.setObjectName("labelrecherche_gamme")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.details_gamme)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(70, 90, 661, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelnom_mod_gamme = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.labelnom_mod_gamme.setObjectName("labelnom_mod_gamme")
        self.horizontalLayout_15.addWidget(self.labelnom_mod_gamme)
        self.nom_mod_gamme = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.nom_mod_gamme.setObjectName("nom_mod_gamme")
        self.horizontalLayout_15.addWidget(self.nom_mod_gamme)
        self.labelcode_mod_gamme = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.labelcode_mod_gamme.setObjectName("labelcode_mod_gamme")
        self.horizontalLayout_15.addWidget(self.labelcode_mod_gamme)
        self.code_mod_gamme = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.code_mod_gamme.setObjectName("code_mod_gamme")
        self.horizontalLayout_15.addWidget(self.code_mod_gamme)
        self.labelmarque_gamme = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.labelmarque_gamme.setObjectName("labelmarque_gamme")
        self.horizontalLayout_15.addWidget(self.labelmarque_gamme)
        self.marque_gamme = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.marque_gamme.setObjectName("marque_gamme")
        self.horizontalLayout_15.addWidget(self.marque_gamme)
        self.gamme = QtWidgets.QTableWidget(self.details_gamme)
        self.gamme.setGeometry(QtCore.QRect(210, 200, 311, 211))
        self.gamme.setObjectName("gamme")
        self.gamme.setColumnCount(3)
        self.gamme.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.gamme.setHorizontalHeaderItem(2, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.details_gamme)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 440, 491, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ajouter_gamme = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ajouter_gamme.setObjectName("ajouter_gamme")
        self.horizontalLayout_3.addWidget(self.ajouter_gamme)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.importer_gamme = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.importer_gamme.setObjectName("importer_gamme")
        self.horizontalLayout_3.addWidget(self.importer_gamme)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.supprimer_gamme = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.supprimer_gamme.setObjectName("supprimer_gamme")
        self.horizontalLayout_3.addWidget(self.supprimer_gamme)
        self.namepage_gamme = QtWidgets.QLabel(self.details_gamme)
        self.namepage_gamme.setGeometry(QtCore.QRect(60, 10, 131, 17))
        self.namepage_gamme.setObjectName("namepage_gamme")
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.details_gamme)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(540, 140, 201, 31))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.rechercher_gamme = QtWidgets.QPushButton(self.horizontalLayoutWidget_18)
        self.rechercher_gamme.setObjectName("rechercher_gamme")
        self.horizontalLayout_20.addWidget(self.rechercher_gamme)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.initialiser_gamme = QtWidgets.QPushButton(self.horizontalLayoutWidget_18)
        self.initialiser_gamme.setObjectName("initialiser_gamme")
        self.horizontalLayout_20.addWidget(self.initialiser_gamme)
        self.stackedWidget.addWidget(self.details_gamme)
        self.ajout_gamme = QtWidgets.QWidget()
        self.ajout_gamme.setObjectName("ajout_gamme")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.ajout_gamme)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(180, 130, 371, 131))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelcode_gamme_aj = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.labelcode_gamme_aj.setObjectName("labelcode_gamme_aj")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelcode_gamme_aj)
        self.code_gamme_aj = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.code_gamme_aj.setObjectName("code_gamme_aj")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.code_gamme_aj)
        self.labelnom_gamme_aj = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.labelnom_gamme_aj.setObjectName("labelnom_gamme_aj")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelnom_gamme_aj)
        self.nom_gamme_aj = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.nom_gamme_aj.setObjectName("nom_gamme_aj")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nom_gamme_aj)
        self.labelmarq_gamme_aj = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.labelmarq_gamme_aj.setObjectName("labelmarq_gamme_aj")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelmarq_gamme_aj)
        self.marq_gamme_aj = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.marq_gamme_aj.setObjectName("marq_gamme_aj")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.marq_gamme_aj)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.ajout_gamme)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(250, 320, 251, 80))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.enregistrer_gamme_aj = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.enregistrer_gamme_aj.setObjectName("enregistrer_gamme_aj")
        self.horizontalLayout_16.addWidget(self.enregistrer_gamme_aj)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.annuler_gamme_aj = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.annuler_gamme_aj.setObjectName("annuler_gamme_aj")
        self.horizontalLayout_16.addWidget(self.annuler_gamme_aj)
        self.namepage_gamme_aj = QtWidgets.QLabel(self.ajout_gamme)
        self.namepage_gamme_aj.setGeometry(QtCore.QRect(60, 20, 131, 17))
        self.namepage_gamme_aj.setObjectName("namepage_gamme_aj")
        self.stackedWidget.addWidget(self.ajout_gamme)
        self.liste_op = QtWidgets.QWidget()
        self.liste_op.setObjectName("liste_op")
        self.labelrecherche_op = QtWidgets.QLabel(self.liste_op)
        self.labelrecherche_op.setGeometry(QtCore.QRect(50, 50, 111, 17))
        self.labelrecherche_op.setObjectName("labelrecherche_op")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.liste_op)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(70, 90, 691, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.recherche_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.recherche_3.setContentsMargins(0, 0, 0, 0)
        self.recherche_3.setObjectName("recherche_3")
        self.labelcode_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelcode_op.setObjectName("labelcode_op")
        self.recherche_3.addWidget(self.labelcode_op)
        self.code_op = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.code_op.setObjectName("code_op")
        self.recherche_3.addWidget(self.code_op)
        self.labelnom_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelnom_op.setObjectName("labelnom_op")
        self.recherche_3.addWidget(self.labelnom_op)
        self.nom_op = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.nom_op.setObjectName("nom_op")
        self.recherche_3.addWidget(self.nom_op)
        self.labelmachine_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelmachine_op.setObjectName("labelmachine_op")
        self.recherche_3.addWidget(self.labelmachine_op)
        self.machine_op = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.machine_op.setObjectName("machine_op")
        self.recherche_3.addWidget(self.machine_op)
        self.tableWidget = QtWidgets.QTableWidget(self.liste_op)
        self.tableWidget.setGeometry(QtCore.QRect(120, 230, 511, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.liste_op)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(80, 450, 621, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.importer_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.importer_op.setObjectName("importer_op")
        self.horizontalLayout_5.addWidget(self.importer_op)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.ajouter_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ajouter_op.setObjectName("ajouter_op")
        self.horizontalLayout_5.addWidget(self.ajouter_op)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.modifier_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.modifier_op.setObjectName("modifier_op")
        self.horizontalLayout_5.addWidget(self.modifier_op)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.supprimer_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.supprimer_op.setObjectName("supprimer_op")
        self.horizontalLayout_5.addWidget(self.supprimer_op)
        self.namepage_liste_op = QtWidgets.QLabel(self.liste_op)
        self.namepage_liste_op.setGeometry(QtCore.QRect(50, 20, 131, 17))
        self.namepage_liste_op.setObjectName("namepage_liste_op")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.liste_op)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(520, 140, 241, 31))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.initialiser_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.initialiser_op.setObjectName("initialiser_op")
        self.horizontalLayout_11.addWidget(self.initialiser_op)
        self.recherche_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.recherche_op.setObjectName("recherche_op")
        self.horizontalLayout_11.addWidget(self.recherche_op)
        self.stackedWidget.addWidget(self.liste_op)
        self.ajout_op = QtWidgets.QWidget()
        self.ajout_op.setObjectName("ajout_op")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.ajout_op)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(250, 90, 371, 211))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelcode_op_aj = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelcode_op_aj.setObjectName("labelcode_op_aj")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelcode_op_aj)
        self.code_op_aj = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.code_op_aj.setObjectName("code_op_aj")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.code_op_aj)
        self.labelnom_op_aj = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelnom_op_aj.setObjectName("labelnom_op_aj")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelnom_op_aj)
        self.nom_op_aj = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nom_op_aj.setObjectName("nom_op_aj")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nom_op_aj)
        self.labelminutage_op_aj = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelminutage_op_aj.setObjectName("labelminutage_op_aj")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelminutage_op_aj)
        self.minute_op_aj = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.minute_op_aj.setObjectName("minute_op_aj")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minute_op_aj)
        self.labelmachine_op_aj = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelmachine_op_aj.setObjectName("labelmachine_op_aj")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelmachine_op_aj)
        self.machine_op_aj = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.machine_op_aj.setObjectName("machine_op_aj")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.machine_op_aj)
        self.critere_op_aj = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.critere_op_aj.setObjectName("critere_op_aj")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.critere_op_aj)
        self.Qcritere = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Qcritere.setObjectName("Qcritere")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Qcritere)
        self.video_op_aj = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.video_op_aj.setObjectName("video_op_aj")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.video_op_aj)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.video_path = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.video_path.setObjectName("video_path")
        self.horizontalLayout.addWidget(self.video_path)
        self.toolButton = QtWidgets.QToolButton(self.formLayoutWidget_2)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.ajout_op)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(270, 340, 311, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ajouter_op_aj = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.ajouter_op_aj.setObjectName("ajouter_op_aj")
        self.horizontalLayout_8.addWidget(self.ajouter_op_aj)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.annuler_op_aj = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.annuler_op_aj.setObjectName("annuler_op_aj")
        self.horizontalLayout_8.addWidget(self.annuler_op_aj)
        self.namepage_ajout_op = QtWidgets.QLabel(self.ajout_op)
        self.namepage_ajout_op.setGeometry(QtCore.QRect(60, 30, 131, 17))
        self.namepage_ajout_op.setObjectName("namepage_ajout_op")
        self.stackedWidget.addWidget(self.ajout_op)
        self.ajouter_equilib = QtWidgets.QWidget()
        self.ajouter_equilib.setObjectName("ajouter_equilib")
        self.recherche_eq = QtWidgets.QLabel(self.ajouter_equilib)
        self.recherche_eq.setGeometry(QtCore.QRect(30, 50, 111, 17))
        self.recherche_eq.setObjectName("recherche_eq")
        self.gridLayoutWidget = QtWidgets.QWidget(self.ajouter_equilib)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 80, 651, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labeldatedeb_eq = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labeldatedeb_eq.setObjectName("labeldatedeb_eq")
        self.gridLayout.addWidget(self.labeldatedeb_eq, 1, 0, 1, 1)
        self.labeldatefin_eq = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labeldatefin_eq.setObjectName("labeldatefin_eq")
        self.gridLayout.addWidget(self.labeldatefin_eq, 1, 2, 1, 1)
        self.labelnb_ouv_eq = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelnb_ouv_eq.setObjectName("labelnb_ouv_eq")
        self.gridLayout.addWidget(self.labelnb_ouv_eq, 1, 4, 1, 1)
        self.nb_ouv_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nb_ouv_eq.setObjectName("nb_ouv_eq")
        self.gridLayout.addWidget(self.nb_ouv_eq, 1, 5, 1, 1)
        self.code_mod_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.code_mod_eq.setObjectName("code_mod_eq")
        self.gridLayout.addWidget(self.code_mod_eq, 0, 1, 1, 1)
        self.labelnom_mod_eq = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelnom_mod_eq.setObjectName("labelnom_mod_eq")
        self.gridLayout.addWidget(self.labelnom_mod_eq, 0, 2, 1, 1)
        self.nom_mod_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nom_mod_eq.setObjectName("nom_mod_eq")
        self.gridLayout.addWidget(self.nom_mod_eq, 0, 3, 1, 1)
        self.labelcadenc_eq = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelcadenc_eq.setObjectName("labelcadenc_eq")
        self.gridLayout.addWidget(self.labelcadenc_eq, 0, 4, 1, 1)
        self.cadenc_eq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cadenc_eq.setObjectName("cadenc_eq")
        self.gridLayout.addWidget(self.cadenc_eq, 0, 5, 1, 1)
        self.labelcode_mod_eq = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelcode_mod_eq.setObjectName("labelcode_mod_eq")
        self.gridLayout.addWidget(self.labelcode_mod_eq, 0, 0, 1, 1)
        self.date_deb_eq = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.date_deb_eq.setObjectName("date_deb_eq")
        self.gridLayout.addWidget(self.date_deb_eq, 1, 1, 1, 1)
        self.date_fin_eq = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.date_fin_eq.setObjectName("date_fin_eq")
        self.gridLayout.addWidget(self.date_fin_eq, 1, 3, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.ajouter_equilib)
        self.tableWidget_2.setGeometry(QtCore.QRect(170, 250, 411, 151))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.ajouter_equilib)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(90, 439, 561, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.valider_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.valider_eq.setObjectName("valider_eq")
        self.horizontalLayout_4.addWidget(self.valider_eq)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.suspendre_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.suspendre_eq.setObjectName("suspendre_eq")
        self.horizontalLayout_4.addWidget(self.suspendre_eq)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.exporter_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.exporter_eq.setObjectName("exporter_eq")
        self.horizontalLayout_4.addWidget(self.exporter_eq)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.annuler_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.annuler_eq.setObjectName("annuler_eq")
        self.horizontalLayout_4.addWidget(self.annuler_eq)
        self.namepage_eq = QtWidgets.QLabel(self.ajouter_equilib)
        self.namepage_eq.setGeometry(QtCore.QRect(30, 10, 131, 17))
        self.namepage_eq.setObjectName("namepage_eq")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.ajouter_equilib)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(520, 180, 241, 31))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.initiliser_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.initiliser_eq.setObjectName("initiliser_eq")
        self.horizontalLayout_12.addWidget(self.initiliser_eq)
        self.rechercher_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.rechercher_eq.setObjectName("rechercher_eq")
        self.horizontalLayout_12.addWidget(self.rechercher_eq)
        self.stackedWidget.addWidget(self.ajouter_equilib)
        self.liste_equilib = QtWidgets.QWidget()
        self.liste_equilib.setObjectName("liste_equilib")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.liste_equilib)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 130, 851, 201))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(8)
        self.tableWidget_4.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.liste_equilib)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(50, 400, 641, 80))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.valider_liste_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.valider_liste_eq.setObjectName("valider_liste_eq")
        self.horizontalLayout_7.addWidget(self.valider_liste_eq)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.reprendre_liste_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.reprendre_liste_eq.setObjectName("reprendre_liste_eq")
        self.horizontalLayout_7.addWidget(self.reprendre_liste_eq)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.supprimer_liste_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.supprimer_liste_eq.setObjectName("supprimer_liste_eq")
        self.horizontalLayout_7.addWidget(self.supprimer_liste_eq)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.exporter_liste_eq = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.exporter_liste_eq.setObjectName("exporter_liste_eq")
        self.horizontalLayout_7.addWidget(self.exporter_liste_eq)
        self.namepage_liste_eq = QtWidgets.QLabel(self.liste_equilib)
        self.namepage_liste_eq.setGeometry(QtCore.QRect(50, 30, 131, 17))
        self.namepage_liste_eq.setObjectName("namepage_liste_eq")
        self.stackedWidget.addWidget(self.liste_equilib)
        self.liste_comp = QtWidgets.QWidget()
        self.liste_comp.setObjectName("liste_comp")
        self.namepage_cmp = QtWidgets.QLabel(self.liste_comp)
        self.namepage_cmp.setGeometry(QtCore.QRect(30, 10, 131, 17))
        self.namepage_cmp.setObjectName("namepage_cmp")
        self.labelrechercher_cmp = QtWidgets.QLabel(self.liste_comp)
        self.labelrechercher_cmp.setGeometry(QtCore.QRect(60, 50, 111, 17))
        self.labelrechercher_cmp.setObjectName("labelrechercher_cmp")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.liste_comp)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 80, 621, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelouvr_cmp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelouvr_cmp.setObjectName("labelouvr_cmp")
        self.horizontalLayout_17.addWidget(self.labelouvr_cmp)
        self.line_ouvr_cmp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.line_ouvr_cmp.setObjectName("line_ouvr_cmp")
        self.horizontalLayout_17.addWidget(self.line_ouvr_cmp)
        self.labelop_cmp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelop_cmp.setObjectName("labelop_cmp")
        self.horizontalLayout_17.addWidget(self.labelop_cmp)
        self.op_cmp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.op_cmp.setObjectName("op_cmp")
        self.horizontalLayout_17.addWidget(self.op_cmp)
        self.labelcomp_cmp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelcomp_cmp.setObjectName("labelcomp_cmp")
        self.horizontalLayout_17.addWidget(self.labelcomp_cmp)
        self.comp_cmp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.comp_cmp.setObjectName("comp_cmp")
        self.horizontalLayout_17.addWidget(self.comp_cmp)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.liste_comp)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(80, 420, 671, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.affecter_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.affecter_cmp.setObjectName("affecter_cmp")
        self.horizontalLayout_18.addWidget(self.affecter_cmp)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem19)
        self.modifier_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.modifier_cmp.setObjectName("modifier_cmp")
        self.horizontalLayout_18.addWidget(self.modifier_cmp)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem20)
        self.supprimer_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.supprimer_cmp.setObjectName("supprimer_cmp")
        self.horizontalLayout_18.addWidget(self.supprimer_cmp)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem21)
        self.export_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.export_cmp.setObjectName("export_cmp")
        self.horizontalLayout_18.addWidget(self.export_cmp)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.liste_comp)
        self.tableWidget_5.setGeometry(QtCore.QRect(110, 230, 611, 181))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.liste_comp)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(540, 120, 241, 31))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.initialiser_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.initialiser_cmp.setObjectName("initialiser_cmp")
        self.horizontalLayout_13.addWidget(self.initialiser_cmp)
        self.rechercher_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.rechercher_cmp.setObjectName("rechercher_cmp")
        self.horizontalLayout_13.addWidget(self.rechercher_cmp)
        self.stackedWidget.addWidget(self.liste_comp)
        self.ajouter_comp = QtWidgets.QWidget()
        self.ajouter_comp.setObjectName("ajouter_comp")
        self.label_12 = QtWidgets.QLabel(self.ajouter_comp)
        self.label_12.setGeometry(QtCore.QRect(70, 20, 151, 17))
        self.label_12.setObjectName("label_12")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.ajouter_comp)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(210, 120, 351, 217))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.labelcin_cmp_aj = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelcin_cmp_aj.setObjectName("labelcin_cmp_aj")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelcin_cmp_aj)
        self.cin_cmp_aj = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.cin_cmp_aj.setObjectName("cin_cmp_aj")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cin_cmp_aj)
        self.labelnom_cmp_aj = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelnom_cmp_aj.setObjectName("labelnom_cmp_aj")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelnom_cmp_aj)
        self.nom_cmp_aj = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.nom_cmp_aj.setObjectName("nom_cmp_aj")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nom_cmp_aj)
        self.labelprenom_cmp_aj = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelprenom_cmp_aj.setObjectName("labelprenom_cmp_aj")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelprenom_cmp_aj)
        self.prenom_cmp_aj = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.prenom_cmp_aj.setObjectName("prenom_cmp_aj")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prenom_cmp_aj)
        self.op_cmp_aj = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.op_cmp_aj.setObjectName("op_cmp_aj")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.op_cmp_aj)
        self.labelallure_cmp_aj = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelallure_cmp_aj.setObjectName("labelallure_cmp_aj")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelallure_cmp_aj)
        self.allure_cmp_aj = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.allure_cmp_aj.setObjectName("allure_cmp_aj")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.allure_cmp_aj)
        self.labelretouche_cmp_aj = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelretouche_cmp_aj.setObjectName("labelretouche_cmp_aj")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelretouche_cmp_aj)
        self.retouche_cmp_aj = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.retouche_cmp_aj.setObjectName("retouche_cmp_aj")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.retouche_cmp_aj)
        self.labelcode_cmp_aj = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelcode_cmp_aj.setObjectName("labelcode_cmp_aj")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelcode_cmp_aj)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.ajouter_comp)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(230, 360, 291, 41))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.enregistrer_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.enregistrer_cmp.setObjectName("enregistrer_cmp")
        self.horizontalLayout_9.addWidget(self.enregistrer_cmp)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem22)
        self.annuler_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.annuler_cmp.setObjectName("annuler_cmp")
        self.horizontalLayout_9.addWidget(self.annuler_cmp)
        self.stackedWidget.addWidget(self.ajouter_comp)
        self.stats = QtWidgets.QWidget()
        self.stats.setObjectName("stats")
        self.page_name_stats = QtWidgets.QLabel(self.stats)
        self.page_name_stats.setGeometry(QtCore.QRect(130, 30, 161, 31))
        self.page_name_stats.setObjectName("page_name_stats")
        self.stackedWidget.addWidget(self.stats)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 25))
        self.menubar.setObjectName("menubar")
        self.menuGestion_Employes = QtWidgets.QMenu(self.menubar)
        self.menuGestion_Employes.setObjectName("menuGestion_Employes")
        self.menuGestion_Operations = QtWidgets.QMenu(self.menubar)
        self.menuGestion_Operations.setObjectName("menuGestion_Operations")
        self.menu_quilibrage = QtWidgets.QMenu(self.menubar)
        self.menu_quilibrage.setObjectName("menu_quilibrage")
        self.menuStatistiqus = QtWidgets.QMenu(self.menubar)
        self.menuStatistiqus.setObjectName("menuStatistiqus")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Liste_Employes = QtWidgets.QAction(MainWindow)
        self.Liste_Employes.setIconVisibleInMenu(False)
        self.Liste_Employes.setObjectName("Liste_Employes")
        self.Competences = QtWidgets.QAction(MainWindow)
        self.Competences.setObjectName("Competences")
        self.Details_Gamme = QtWidgets.QAction(MainWindow)
        self.Details_Gamme.setObjectName("Details_Gamme")
        self.Details_Operation = QtWidgets.QAction(MainWindow)
        self.Details_Operation.setObjectName("Details_Operation")
        self.Creer_equilibrage = QtWidgets.QAction(MainWindow)
        self.Creer_equilibrage.setObjectName("Creer_equilibrage")
        self.Liste_equilibrage = QtWidgets.QAction(MainWindow)
        self.Liste_equilibrage.setObjectName("Liste_equilibrage")
        self.menuGestion_Employes.addAction(self.Liste_Employes)
        self.menuGestion_Employes.addAction(self.Competences)
        self.menuGestion_Operations.addAction(self.Details_Gamme)
        self.menuGestion_Operations.addAction(self.Details_Operation)
        self.menu_quilibrage.addAction(self.Creer_equilibrage)
        self.menu_quilibrage.addAction(self.Liste_equilibrage)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuGestion_Employes.menuAction())
        self.menubar.addAction(self.menuGestion_Operations.menuAction())
        self.menubar.addAction(self.menu_quilibrage.menuAction())
        self.menubar.addAction(self.menuStatistiqus.menuAction())

        self.retranslateUi(MainWindow)
        #menu: liste employes
        self.Liste_Employes.triggered.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_emp))
        #menu: liste competences
        self.Competences.triggered.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_comp))
        #menu: details gamme
        self.Details_Gamme.triggered.connect(partial(self.stackedWidget.setCurrentWidget,self.details_gamme))
        #menu: details operantion
        self.Details_Operation.triggered.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_op))
        #menu: creer equilibrage
        self.Creer_equilibrage.triggered.connect(partial(self.stackedWidget.setCurrentWidget,self.ajouter_equilib))
        #menu: liste equilibrages
        self.Liste_equilibrage.triggered.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_equilib))
        #menu: statistiques
        #self.menuStatistiqus.activated.connect(partial(self.stackedWidget.setCurrentWidget,self.stats))
        #menu: accueil
        #self.menuHome.activated.connect(partial(self.stackedWidget.setCurrentWidget,self.welcome))
        
        #bouton ajouter: liste employes => ajouter employes
        self.ajouter_emp.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.ajouter_employe))
        #bouton annuler: ajouter employes => liste employes
        self.annuler_emp.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_emp))
        #bouton ajouter: details gamme => ajouter gamme
        self.ajouter_gamme.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.ajout_gamme))
        #bouton annuler: ajouter gamme => details gamme
        self.annuler_gamme_aj.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.details_gamme))
        #bouton ajouter: liste operations => ajouter operation
        self.ajouter_op.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.ajout_op))
        #bouton annuler: ajouter operation => liste operations
        self.annuler_op_aj.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_op))
        #bouton ajouter: liste competences => ajouter competence
        self.affecter_cmp.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.ajouter_comp))
        #bouton annuler: ajouter competence => liste competences
        self.annuler_cmp.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.liste_comp))
        #bouton annuler: ajouter equilibrage => accueil
        self.annuler_eq.clicked.connect(partial(self.stackedWidget.setCurrentWidget,self.welcome))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.page_name_welcome.setText(_translate("MainWindow", "WELCOME PAGE"))
        self.labelrecherche_emp.setText(_translate("MainWindow", "Rechercher par:"))
        item = self.table_emp.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Matricule"))
        item = self.table_emp.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CIN"))
        item = self.table_emp.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nom"))
        item = self.table_emp.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Prénom"))
        item = self.table_emp.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Naissance"))
        item = self.table_emp.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date d\'Embauche"))
        self.namepage_emp.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Liste Employés</span></p></body></html>"))
        self.labelnaissance_emp.setText(_translate("MainWindow", "Date Naissance:"))
        self.labelmatricul_emp.setText(_translate("MainWindow", "Matricule:"))
        self.labelprenom_emp.setText(_translate("MainWindow", "Prénom :"))
        self.labelcin_emp.setText(_translate("MainWindow", "CIN :"))
        self.labelembauche_emp.setText(_translate("MainWindow", "Date Embauche:"))
        self.labelnom_emp.setText(_translate("MainWindow", "Nom :"))
        self.ajouter_emp.setText(_translate("MainWindow", "Ajouter"))
        self.importer_emp.setText(_translate("MainWindow", "Importer"))
        self.Modifier_emp.setText(_translate("MainWindow", "Modifier"))
        self.supprimer_emp.setText(_translate("MainWindow", "Supprimer"))
        self.rechercher_emp.setText(_translate("MainWindow", "Rechercher"))
        self.initialiser_emp.setText(_translate("MainWindow", "Initialiser"))
        self.label_mat_aj_emp.setText(_translate("MainWindow", "Matricule :"))
        self.label_cin_aj_emp.setText(_translate("MainWindow", "CIN :"))
        self.label_nom_aj_emp.setText(_translate("MainWindow", "Nom :"))
        self.label_prenom_aj_emp.setText(_translate("MainWindow", "Prénom :"))
        self.label_emb_aj_emp.setText(_translate("MainWindow", "Date Embauche :"))
        self.label_photo_aj_emp.setText(_translate("MainWindow", "Photo :"))
        self.parcourir.setText(_translate("MainWindow", "..."))
        self.label_naiss_aj_emp.setText(_translate("MainWindow", "Date Naissance :"))
        self.enregistrer_emp.setText(_translate("MainWindow", "Enregistrer"))
        self.annuler_emp.setText(_translate("MainWindow", "Annuler"))
        self.namepage_aj_emp.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Ajouter Employés</span></p></body></html>"))
        self.labelrecherche_gamme.setText(_translate("MainWindow", "Rechercher par:"))
        self.labelnom_mod_gamme.setText(_translate("MainWindow", "Nom Modèle:"))
        self.labelcode_mod_gamme.setText(_translate("MainWindow", "Code Modèle:"))
        self.labelmarque_gamme.setText(_translate("MainWindow", "Marque:"))
        item = self.gamme.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom Modèle"))
        item = self.gamme.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code modèle"))
        item = self.gamme.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Marque"))
        self.ajouter_gamme.setText(_translate("MainWindow", "Ajouter"))
        self.importer_gamme.setText(_translate("MainWindow", "Importer"))
        self.supprimer_gamme.setText(_translate("MainWindow", "Supprimer"))
        self.namepage_gamme.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">détails Gamme</span></p></body></html>"))
        self.rechercher_gamme.setText(_translate("MainWindow", "Rechercher"))
        self.initialiser_gamme.setText(_translate("MainWindow", "Initialiser"))
        self.labelcode_gamme_aj.setText(_translate("MainWindow", "Code Modèle:"))
        self.labelnom_gamme_aj.setText(_translate("MainWindow", "Nom Modèle:"))
        self.labelmarq_gamme_aj.setText(_translate("MainWindow", "Marque:"))
        self.enregistrer_gamme_aj.setText(_translate("MainWindow", "Enregistrer"))
        self.annuler_gamme_aj.setText(_translate("MainWindow", "Annuler"))
        self.namepage_gamme_aj.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Ajouter Gamme</span></p></body></html>"))
        self.labelrecherche_op.setText(_translate("MainWindow", "Rechercher par: "))
        self.labelcode_op.setText(_translate("MainWindow", "Code Opération:"))
        self.labelnom_op.setText(_translate("MainWindow", "Nom Opération:"))
        self.labelmachine_op.setText(_translate("MainWindow", "Machine: "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code Opération"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom Opération"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Minutage"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Machine"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Critère de Qualité"))
        self.importer_op.setText(_translate("MainWindow", "Importer"))
        self.ajouter_op.setText(_translate("MainWindow", "Ajouter"))
        self.modifier_op.setText(_translate("MainWindow", "Modifier"))
        self.supprimer_op.setText(_translate("MainWindow", "Supprimer"))
        self.namepage_liste_op.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Liste Opérations</span></p></body></html>"))
        self.initialiser_op.setText(_translate("MainWindow", "Initialiser"))
        self.recherche_op.setText(_translate("MainWindow", "Rechercher"))
        self.labelcode_op_aj.setText(_translate("MainWindow", "Code Opération:"))
        self.labelnom_op_aj.setText(_translate("MainWindow", "Nom Opération:"))
        self.labelminutage_op_aj.setText(_translate("MainWindow", "Minutage:"))
        self.labelmachine_op_aj.setText(_translate("MainWindow", "Machine:"))
        self.critere_op_aj.setText(_translate("MainWindow", "Critère de Qualité:"))
        self.video_op_aj.setText(_translate("MainWindow", "Vidéo:"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.ajouter_op_aj.setText(_translate("MainWindow", "Enregistrer"))
        self.annuler_op_aj.setText(_translate("MainWindow", "Annuler"))
        self.namepage_ajout_op.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Ajouter Opération</span></p></body></html>"))
        self.recherche_eq.setText(_translate("MainWindow", "Rechercher par:"))
        self.labeldatedeb_eq.setText(_translate("MainWindow", "Date Début:"))
        self.labeldatefin_eq.setText(_translate("MainWindow", "Date Fin:"))
        self.labelnb_ouv_eq.setText(_translate("MainWindow", "Nbre Ouvrières:"))
        self.labelnom_mod_eq.setText(_translate("MainWindow", "Nom Modèle:"))
        self.labelcadenc_eq.setText(_translate("MainWindow", "Cadence:"))
        self.labelcode_mod_eq.setText(_translate("MainWindow", "Code Modèle:"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code Opération"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom Opération"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Code Employé"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nom Employé"))
        self.valider_eq.setText(_translate("MainWindow", "Valider"))
        self.suspendre_eq.setText(_translate("MainWindow", "Suspendre"))
        self.exporter_eq.setText(_translate("MainWindow", "Exporter"))
        self.annuler_eq.setText(_translate("MainWindow", "Annuler"))
        self.namepage_eq.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Creer Equilibrage</span></p></body></html>"))
        self.initiliser_eq.setText(_translate("MainWindow", "Initialiser"))
        self.rechercher_eq.setText(_translate("MainWindow", "Rechercher"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code Equilibrage"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Code Modèle"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nom Modèle"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Début"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Fin"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Cadence"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nbre Ouvrières"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Etat"))
        self.valider_liste_eq.setText(_translate("MainWindow", "Valider"))
        self.reprendre_liste_eq.setText(_translate("MainWindow", "Reprendre"))
        self.supprimer_liste_eq.setText(_translate("MainWindow", "Supprimer"))
        self.exporter_liste_eq.setText(_translate("MainWindow", "Exporter"))
        self.namepage_liste_eq.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Liste Equilibrages</span></p></body></html>"))
        self.namepage_cmp.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Liste Competence</span></p></body></html>"))
        self.labelrechercher_cmp.setText(_translate("MainWindow", "Rechercher par: "))
        self.labelouvr_cmp.setText(_translate("MainWindow", "Ouvrière :"))
        self.labelop_cmp.setText(_translate("MainWindow", "Opération :"))
        self.labelcomp_cmp.setText(_translate("MainWindow", "Compétence :"))
        self.affecter_cmp.setText(_translate("MainWindow", "Affecter"))
        self.modifier_cmp.setText(_translate("MainWindow", "Modifier"))
        self.supprimer_cmp.setText(_translate("MainWindow", "Supprimer"))
        self.export_cmp.setText(_translate("MainWindow", "Exporter Grille"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CIN"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nom"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prénom"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Code Opération"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Nom Opération"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Compétence"))
        self.initialiser_cmp.setText(_translate("MainWindow", "Initialiser"))
        self.rechercher_cmp.setText(_translate("MainWindow", "Rechercher"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Ajouter Competence</span></p></body></html>"))
        self.labelcin_cmp_aj.setText(_translate("MainWindow", "CIN :"))
        self.labelnom_cmp_aj.setText(_translate("MainWindow", "Nom :"))
        self.labelprenom_cmp_aj.setText(_translate("MainWindow", "Prénom : "))
        self.labelallure_cmp_aj.setText(_translate("MainWindow", "Allure :"))
        self.labelretouche_cmp_aj.setText(_translate("MainWindow", "Taux de Retouche :"))
        self.labelcode_cmp_aj.setText(_translate("MainWindow", "Code Opération :"))
        self.enregistrer_cmp.setText(_translate("MainWindow", "Enregistrer"))
        self.annuler_cmp.setText(_translate("MainWindow", "Annuler"))
        self.page_name_stats.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aaff;\">Page des Statistiques</span></p></body></html>"))
        self.menuGestion_Employes.setTitle(_translate("MainWindow", "Gestion Employés"))
        self.menuGestion_Operations.setTitle(_translate("MainWindow", "Gestion Opérations"))
        self.menu_quilibrage.setTitle(_translate("MainWindow", "Équilibrage"))
        self.menuStatistiqus.setTitle(_translate("MainWindow", "Consulter Statistiques"))
        self.menuHome.setTitle(_translate("MainWindow", "Accueil"))
        self.Liste_Employes.setText(_translate("MainWindow", "Liste Employés"))
        self.Competences.setText(_translate("MainWindow", "Compétences"))
        self.Details_Gamme.setText(_translate("MainWindow", "Détails Gamme"))
        self.Details_Operation.setText(_translate("MainWindow", "Détails Opération"))
        self.Creer_equilibrage.setText(_translate("MainWindow", "Créer Équilibrage"))
        self.Liste_equilibrage.setText(_translate("MainWindow", "Liste Équilibrage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

