# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_liste_comp.ui'
#
# Created: Wed Jun 10 08:12:09 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Liste_Competence(object):
    def setupUi(self, Form):
        Form.setObjectName("Liste des Competences")
        Form.resize(799, 593)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(510, 180, 241, 31))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.initialiser_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.initialiser_cmp.setObjectName("initialiser_cmp")
        self.horizontalLayout_13.addWidget(self.initialiser_cmp)
        self.rechercher_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.rechercher_cmp.setObjectName("rechercher_cmp")
        self.horizontalLayout_13.addWidget(self.rechercher_cmp)
        self.namepage_cmp = QtWidgets.QLabel(Form)
        self.namepage_cmp.setGeometry(QtCore.QRect(10, 70, 131, 17))
        self.namepage_cmp.setObjectName("namepage_cmp")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(60, 480, 691, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.affecter_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.affecter_cmp.setObjectName("affecter_cmp")
        self.horizontalLayout_18.addWidget(self.affecter_cmp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.modifier_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.modifier_cmp.setObjectName("modifier_cmp")
        self.horizontalLayout_18.addWidget(self.modifier_cmp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.supprimer_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.supprimer_cmp.setObjectName("supprimer_cmp")
        self.horizontalLayout_18.addWidget(self.supprimer_cmp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.export_cmp = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.export_cmp.setObjectName("export_cmp")
        self.horizontalLayout_18.addWidget(self.export_cmp)
        self.labelrechercher_cmp = QtWidgets.QLabel(Form)
        self.labelrechercher_cmp.setGeometry(QtCore.QRect(40, 110, 111, 17))
        self.labelrechercher_cmp.setObjectName("labelrechercher_cmp")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 140, 661, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelouvr_cmp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelouvr_cmp.setObjectName("labelouvr_cmp")
        self.horizontalLayout_17.addWidget(self.labelouvr_cmp)
        self.line_ouvr_cmp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.line_ouvr_cmp.setObjectName("line_ouvr_cmp")
        self.horizontalLayout_17.addWidget(self.line_ouvr_cmp)
        self.labelop_cmp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelop_cmp.setObjectName("labelop_cmp")
        self.horizontalLayout_17.addWidget(self.labelop_cmp)
        self.op_cmp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.op_cmp.setObjectName("op_cmp")
        self.horizontalLayout_17.addWidget(self.op_cmp)
        self.labelcomp_cmp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelcomp_cmp.setObjectName("labelcomp_cmp")
        self.horizontalLayout_17.addWidget(self.labelcomp_cmp)
        self.comp_cmp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.comp_cmp.setObjectName("comp_cmp")
        self.horizontalLayout_17.addWidget(self.comp_cmp)
        self.competence = QtWidgets.QTableView(Form)
        self.competence.setGeometry(QtCore.QRect(75, 241, 671, 211))
        self.competence.setObjectName("competence")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Liste des Competences", "Liste des Competences"))
        self.initialiser_cmp.setText(_translate("Form", "Initialiser"))
        self.rechercher_cmp.setText(_translate("Form", "Rechercher"))
        self.namepage_cmp.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#55aaff;\">Liste Competence</span></p></body></html>"))
        self.affecter_cmp.setText(_translate("Form", "Affecter"))
        self.modifier_cmp.setText(_translate("Form", "Modifier"))
        self.supprimer_cmp.setText(_translate("Form", "Supprimer"))
        self.export_cmp.setText(_translate("Form", "Exporter Grille"))
        self.labelrechercher_cmp.setText(_translate("Form", "Rechercher par: "))
        self.labelouvr_cmp.setText(_translate("Form", "Matricule Ouvrière :"))
        self.labelop_cmp.setText(_translate("Form", "Opération :"))
        self.labelcomp_cmp.setText(_translate("Form", "Compétence :"))

