# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_liste_op.ui'
#
# Created: Tue Jun  9 17:13:22 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Liste_Op(object):
    def setupUi(self, Form):
        Form.setObjectName("Liste des Opérations")
        Form.resize(756, 564)
        self.labelrecherche_op = QtWidgets.QLabel(Form)
        self.labelrecherche_op.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.labelrecherche_op.setObjectName("labelrecherche_op")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 80, 691, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.recherche_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.recherche_3.setContentsMargins(0, 0, 0, 0)
        self.recherche_3.setObjectName("recherche_3")
        self.labelcode_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelcode_op.setObjectName("labelcode_op")
        self.recherche_3.addWidget(self.labelcode_op)
        self.code_op = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.code_op.setObjectName("code_op")
        self.recherche_3.addWidget(self.code_op)
        self.labelnom_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelnom_op.setObjectName("labelnom_op")
        self.recherche_3.addWidget(self.labelnom_op)
        self.nom_op = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.nom_op.setObjectName("nom_op")
        self.recherche_3.addWidget(self.nom_op)
        self.labelmachine_op = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelmachine_op.setObjectName("labelmachine_op")
        self.recherche_3.addWidget(self.labelmachine_op)
        self.machine_op = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.machine_op.setObjectName("machine_op")
        self.recherche_3.addWidget(self.machine_op)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(40, 200, 671, 192))
        self.tableView.setObjectName("tableView")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(480, 130, 241, 31))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.initialiser_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.initialiser_op.setObjectName("initialiser_op")
        self.horizontalLayout_11.addWidget(self.initialiser_op)
        self.recherche_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.recherche_op.setObjectName("recherche_op")
        self.horizontalLayout_11.addWidget(self.recherche_op)
        self.namepage_liste_op = QtWidgets.QLabel(Form)
        self.namepage_liste_op.setGeometry(QtCore.QRect(275, 10, 450, 30))
        self.namepage_liste_op.setObjectName("namepage_liste_op")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(80, 460, 621, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.importer_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.importer_op.setObjectName("importer_op")
        self.horizontalLayout_5.addWidget(self.importer_op)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.ajouter_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ajouter_op.setObjectName("ajouter_op")
        self.horizontalLayout_5.addWidget(self.ajouter_op)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.modifier_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.modifier_op.setObjectName("modifier_op")
        self.horizontalLayout_5.addWidget(self.modifier_op)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.supprimer_op = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.supprimer_op.setObjectName("supprimer_op")
        self.horizontalLayout_5.addWidget(self.supprimer_op)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Liste Des Operations", "Liste des Opérations"))
        self.labelrecherche_op.setText(_translate("Form", "Rechercher par: "))
        self.labelcode_op.setText(_translate("Form", "Code Opération:"))
        self.labelnom_op.setText(_translate("Form", "Nom Opération:"))
        self.labelmachine_op.setText(_translate("Form", "Machine: "))
        self.initialiser_op.setText(_translate("Form", "Initialiser"))
        self.recherche_op.setText(_translate("Form", "Rechercher"))
        self.namepage_liste_op.setText(_translate("Form", "<html><head/><body><h1><span style=\" color:#55aaff;\">Liste des Opérations</span></h1></body></html>"))
        self.importer_op.setText(_translate("Form", "Importer"))
        self.ajouter_op.setText(_translate("Form", "Ajouter"))
        self.modifier_op.setText(_translate("Form", "Modifier"))
        self.supprimer_op.setText(_translate("Form", "Supprimer"))

